[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@openzeppelin/=node_modules/@openzeppelin/",
]
# Some deploy tests use vm.setEnv which writes to the shared OS process env.
# Running tests serially prevents race conditions between those tests.
jobs = 1

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
